<?php

global $_LANGMAIL;
$_LANGMAIL = array();
$_LANGMAIL['Welcome!'] = 'Bem-vindo!';
$_LANGMAIL['Process the payment of your order'] = 'Proceda à finalização da sua encomenda';
$_LANGMAIL['Your message has been correctly sent #ct%1$s #tc%2$s'] = 'A sua mensagem foi enviada com sucesso #ct%1$s #tc%2$s';
$_LANGMAIL['Your message has been correctly sent'] = 'A sua mensagem foi enviada com sucesso';
$_LANGMAIL['Message from contact form'] = 'Mensagem de Cliente através de Formulário de Contacto';
$_LANGMAIL['New credit slip regarding your order'] = 'New credit slip regarding your order';
$_LANGMAIL['The virtual product that you bought is available for download'] = '';
$_LANGMAIL['Virtual product to download'] = 'Virtual product(s) available for download';
$_LANGMAIL['Fwd: Customer message'] = 'Fwd: Customer message';
$_LANGMAIL['Your guest account has been transformed into a customer account'] = '';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Your guest account has been transformed to a customer account';
$_LANGMAIL['Package in transit'] = 'A sua encomenda está a caminho';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Log: You have a new alert from your shop';
$_LANGMAIL['Your order has been changed'] = 'A sua encomenda foi alterada';
$_LANGMAIL['Order confirmation'] = 'Order confirmation';
$_LANGMAIL['Message from a customer'] = 'Message from a customer';
$_LANGMAIL['New message regarding your order'] = 'New message regarding your order';
$_LANGMAIL['Your order return state has changed'] = 'Your order return status has changed';
$_LANGMAIL['Your order return status has changed'] = '';
$_LANGMAIL['Your new password'] = 'A sua nova Palavra-passe';
$_LANGMAIL['Password query confirmation'] = 'Forgot password';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'An answer to your message is available #ct%1$s #tc%2$s';
$_LANGMAIL['New voucher regarding your order %s'] = 'New voucher for your order %s';
$_LANGMAIL['New voucher for your order %s'] = '';
$_LANGMAIL['New voucher for your order #%s'] = '';
$_LANGMAIL['Newsletter confirmation'] = '';
$_LANGMAIL['Email verification'] = 'Email verification';
$_LANGMAIL['Newsletter voucher'] = 'Newsletter voucher';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Your wishlist\'s link';
$_LANGMAIL['Message from %1$s %2$s'] = 'Message from %1$s %2$s';
$_LANGMAIL['Product quantity'] = '';
$_LANGMAIL['Errors import'] = '';
$_LANGMAIL['Your cart and your discount'] = 'Discount offer for items in your cart';
$_LANGMAIL['Thanks for your order'] = 'Thanks for your order!';
$_LANGMAIL['You are one of our best customers'] = 'Thank you for being one of our best customers';
$_LANGMAIL['We miss you'] = 'We miss you';
$_LANGMAIL['Product available'] = 'Your watched product is now available';
$_LANGMAIL['New order : #%d - %s'] = '';
$_LANGMAIL['Stock coverage'] = 'Stock coverage';
$_LANGMAIL['Product out of stock'] = 'One or more products are almost out of stock';
$_LANGMAIL['Error reporting from your PayPal module'] = '';
$_LANGMAIL['Congratulations!'] = 'Congratulations!';
$_LANGMAIL['Referral Program'] = '';
$_LANGMAIL['%1$s sent you a link to %2$s'] = '%1$s enviou um link a %2$s';

?>